ksi2/ksi/accountksi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from .views import *
app_name = 'accountksi'
urlpatterns = [
    path('accountksi/register/', register, name='register'),
    path('accountksi/logout/', logout_user, name='logout_user'),
    path('accountksi/login/', user_login, name='login'),
    path('accountksi/password-reset/', auth_views.PasswordResetView.as_view(template_name='accountksi/password_reset_form.html', email_template_name='accountksi/password_reset_email.html', success_url = reverse_lazy('accountksi:password_reset_done')), name='password_reset'),
    path('accountksi/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accountksi/password_reset_done.html'), name='password_reset_done'),
    path(r'accountksi/password-reset/confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='accountksi/password_reset_confirm.html',success_url = reverse_lazy('accountksi:password_reset_complete')), name='password_reset_confirm'),
    path('accountksi/password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accountksi/password_reset_complete.html'), name='password_reset_complete'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ksi2/ksi/ksi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from tutorial.views import *
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('tutorial.urls')),
    path('', include('accountksi.urls')),
    path('success_solution/', success_solution, name='success_solution'),
    path('update_solution/', update_solution, name='update_solution'),
    path('sandbox/', sandbox, name='sandbox'),
    path('tips&tricks/', tips, name='tips'),
    path('get_tricks/', get_tricks, name='get_tricks'),
    path('accounts/', include('allauth.urls')),
    path('courses/', courses, name = 'courses'),
    path('profile/', profile, name = 'profile'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found
handler500 = page_not_found1

ksi2/ksi/tutorial/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from tutorial.views import page_not_found

from .views import *
app_name = 'tutorial'
urlpatterns = [
    path('', index, name='index'),
    path('tutorial/<slug:theme>/', theory, name='theory'),
    path('tutorial/<slug:theme>/<slug:task>', task, name='task'),
]
handler404 = page_not_found
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ksi2/ksi/tutorial/models.py
import uuid

from django.conf import settings
from django.contrib.auth.models import  User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils  import timezone
from datetime import *



def task_avatar_directory_path(instance, filename):
    return 'avat_task/{}'.format(filename)


def theme_avatar_directory_path(instance, filename):
    return 'avat_theme/{}'.format( filename)

def course_avatar_directory_path(instance, filename):
    return 'avat_course/{}'.format( filename)

def task_testfile_directory_path(instance, filename):
    return 'test_files/{}.txt'.format(filename)





class Theme(models.Model):
    title = models.CharField(max_length=200)
    title_url = models.CharField(max_length=200)
    description = models.TextField()
    order_num = models.IntegerField()
    avatar = models.ImageField(upload_to=theme_avatar_directory_path)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return self.title_url

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'


class Task(models.Model):
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=255, unique=True, verbose_name='URL')
    default_code = models.TextField(default='')
    title = models.CharField(max_length=200)
    content = models.TextField()
    test = models.TextField(blank=True)
    test_file = models.FileField(blank=True, upload_to=task_testfile_directory_path)
    avatar = models.ImageField(upload_to=task_avatar_directory_path, blank=True)
    hint = models.TextField()
    author_solution = models.TextField()
    difficulty = models.IntegerField()
    available = models.BooleanField(default=True)
    withfile = models.IntegerField(default=0)
    withtest = models.IntegerField(default=1)
    withimg = models.IntegerField(default=0)
    solved_tasks = models.ManyToManyField(settings.AUTH_USER_MODEL, through='UserTask')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return self.title_url

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    @property
    def has_hint(self):
        return len(self.hint) > 0

    @property
    def user_solution_range(self):
        t = Task.objects.get(slug=self.slug)
        l = len(t.usertask_set.all().filter(solved_task__pk=t.pk))
        return range(min(l, 5))

        

    @property
    def black_range_for_difficulty(self):
        return range(1, self.difficulty + 1)


    @property
    def white_range_for_difficulty(self):
        return range(self.difficulty, 5)


    @property
    def difficulty_color(self):
        dc = {1: '#008000', 2: '#006400', 3: '#CD5C5C', 4: '#8B0000', 5: 'black'}
        return dc[self.difficulty]


class UserTask(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    solved_task = models.ForeignKey(Task, on_delete=models.CASCADE)
    user_solution = models.TextField()
    # # t = timezone.localtime(timezone.now())
    # print(datetime(2000, 1, 1, 0, 0, tzinfo=timezone.utc).isoformat())
    first_view = models.DateTimeField( default = datetime(2000, 1, 1, 0, 0, tzinfo=timezone.utc))
    finish = models.DateTimeField( default = datetime(2000, 1, 1, 0, 0, tzinfo=timezone.utc))
    attemptions = models.IntegerField(default = 0)
    ratio = models.FloatField(default = 0)

    class Meta:
        verbose_name = 'Юзер и решение'
        verbose_name_plural = 'Юзера и решения'

    def __str__(self):
        return self.user.username+':'+self.solved_task.title


class Trick(models.Model):
    title = models.CharField(max_length=200)
    code = models.TextField()
    comment = models.TextField()

    class Meta:
        verbose_name = 'Трюк'
        verbose_name_plural = 'Трюки'

    def __str__(self):
        return self.title

    @property
    def range_without_0(self):
        return range(1, 4)


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    donated = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        a = Profile.objects.create(user=instance)
        a.save()
        #instance.profile.save()

class Course(models.Model):
    title = models.CharField(max_length=200)
    theme = models.ManyToManyField(Theme, blank = True)
    task = models.ManyToManyField(Task, blank = True)
    profile = models.ManyToManyField(Profile, blank = True)
    # avatar = models.ImageField(upload_to=course_avatar_directory_path, blank=True)
    price = models.IntegerField()
    priority = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_themes(self):
        return ','.join([str(x) for x in self.theme.all()])

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'

ksi2/ksi/tutorial/views.py
import json
import random

from django.contrib.auth.models import User
from django.http import HttpResponse   #, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from itertools import chain
from .models import *
from django.utils  import timezone as dj_tz
from datetime import *


def index(request):
    context = {
        'title': 'Учебник',
        'themes': Theme.objects.order_by('order_num')
    }
    if request.user.is_authenticated:
        p = request.user.profile_set.get(user__pk = request.user.pk)
        context['locked_themes'] = themes_locked_for_profile(p)
    else:
        context['locked_themes'] = Theme.objects.filter(course__pk__in = Course.objects.all())
    return render(request, 'tutorial/index.html', context)


def theory(request, theme):
    context = {
        'theme': get_object_or_404(Theme, title_url = theme) ,
        'title': Theme.objects.get(title_url = theme).title,
        'themes': Theme.objects.order_by('order_num')
    }
    if request.user.is_authenticated:
        if context['theme'] in themes_locked_for_profile(request):
             return redirect('/courses')
        st = [i for i in Task.objects.all() if request.user.usertask_set.all().filter(solved_task__pk=i.pk).exists()]
        context['st'] = st
        context['locked_tasks'] = tasks_locked_for_profile(request)
        context['locked_themes'] = themes_locked_for_profile(request)
        return render(request, 'tutorial/theory_'+context['theme'].title_url+'.html', context)
    else:
        return redirect('/accountksi/register?next=/courses')


def task(request, theme, task):
    t = Task.objects.get(slug=task)
    dc = {1: '#008000', 2: '#006400', 3: '#CD5C5C', 4: '#8B0000', 5: 'black'}
    context = {
        'theme': Theme.objects.get(title_url=theme),
        'title': t.title,
        'task': t,
        'themes': Theme.objects.order_by('order_num'),
        'code':t.default_code,
    }
    if request.user.is_authenticated:
        if context['task'] in tasks_locked_for_profile(request):
            return redirect('/courses')
        st = [i for i in Task.objects.all() if request.user.usertask_set.all().filter(solved_task__pk=i.pk).exists()]
        context['st'] = st
        context['locked_tasks'] = tasks_locked_for_profile(request)
        context['locked_themes'] = themes_locked_for_profile(request)
        user_task = request.user.usertask_set.all().filter(solved_task__pk=t.pk)
        context['exists'] = int(user_task.exists())

        if t.withfile == 1:
            context['test_file'] = str(t.test_file.read())[2:-1]
        if t.withtest == 1:
            context['rangetests'] = range(len(json.loads(t.test)))
        if request.user.usertask_set.all().filter(solved_task__pk=t.pk).exists():
            context['code'] = request.user.usertask_set.all().get(solved_task__pk=t.pk).user_solution
    return render(request, 'tutorial/task.html', context)

def themes_locked_for_profile(request):
    p =  request.user.profile_set.get(user__pk = request.user.pk)
    dtms = set(chain(*[x.theme.all() for x in Course.objects.filter(profile__pk=p.pk)]))
    tms = set(Theme.objects.filter(course__pk__in = Course.objects.all()))
    return tms-dtms

def tasks_locked_for_profile(request):
    p =  request.user.profile_set.get(user__pk = request.user.pk)
    donated_tasks = set(chain(*[x.task.all() for x in Course.objects.filter(profile__pk=p.pk)]))
    dtms = set(chain(*[x.theme.all() for x in Course.objects.filter(profile__pk=p.pk)]))
    donated_by_themes = set(chain(*[x.task_set.all() for x in dtms]))
    tasks = set(Task.objects.filter(course__pk__in = Course.objects.all()))
    themes = set(Theme.objects.filter(course__pk__in = Course.objects.all()))
    task_from_themes = set(chain(*[x.task_set.all() for x in themes]))
    return tasks.union(task_from_themes) - donated_tasks.union(donated_by_themes)

def tasks_donated_for_profile(request):
    p =  request.user.profile_set.get(user__pk = request.user.pk)
    dontated_tasks = set(chain(*[x.task.all() for x in Course.objects.filter(profile__pk=p.pk)]))
    return dontated_tasks

def from_end_cleaner(s):
    i = len(s)-1
    while s[i] in [' ', '\n']:
        i-=1
    return s[:i+1]

def success_solution(request):
    if request.method == 'POST':
        req_task = request.POST['slug']
        req_solution = request.POST['solution']
        req_user = request.POST['user']
        bd_user = User.objects.get(username=req_user)
        bd_task = Task.objects.get(slug=req_task)
        t = bd_task.usertask_set.all().filter(solved_task__pk=bd_task.pk).exclude(user = request.user)
        if len(t)==0:
            z = {}
        else:
            t = random.sample(list(t), max(1, len(t)))
            z = {x.user.username:from_end_cleaner(x.user_solution) for x in t}
        ut = bd_user.usertask_set.all().get(solved_task__pk=bd_task.pk)
        ut.user_solution = from_end_cleaner(req_solution)
        if ut.finish ==  datetime(2000, 1, 1, 0, 0, tzinfo=timezone.utc):
            ut.finish =  dj_tz.localtime(dj_tz.now())
        ut.save()
        ausol= Task.objects.get(slug = req_task).author_solution
        y = json.dumps({'author_solution':ausol, 'other':z}, ensure_ascii=False)
        return HttpResponse(y, status=200)

def update_solution(request):
    if request.method == 'POST':
        req_task = request.POST['slug']
        req_solution = request.POST['solution']
        req_user = request.POST['user']
        req_ratio = request.POST['ratio']
        bd_user = User.objects.get(username=req_user)
        bd_task = Task.objects.get(slug=req_task)
        solution_set = bd_user.usertask_set.all().filter(solved_task__pk=bd_task.pk)
        if solution_set.exists():
            sol = solution_set[0]
            if  sol.finish ==  datetime(2000, 1, 1, 0, 0, tzinfo=timezone.utc):
                sol.attemptions += 1
                sol.user_solution = from_end_cleaner(req_solution)
                sol.save()
        else:
            UserTask.objects.create(user=bd_user, solved_task=bd_task, user_solution=from_end_cleaner(req_solution), first_view =  dj_tz.localtime(dj_tz.now()), ratio = req_ratio, attemptions = 1 )
        return HttpResponse(status=200)


def sandbox(request):
    context = {
        'title': 'Песочница',
        'themes': Theme.objects.order_by('order_num'),
        'code':'',
    }
    if request.user.is_authenticated:
        st = [i for i in Task.objects.all() if request.user.usertask_set.all().filter(solved_task__pk=i.pk).exists()]
        
        context['st'] = st
    return render(request, 'tutorial/sandbox.html', context)


def get_tricks(request):
    if request.method == 'GET':
        tricks = random.sample(list(Trick.objects.all()), 2)
        trick_titles = [x.title for x in tricks]
        trick_codes = [x.code for x in tricks]
        trick_comments = [x.comment for x in tricks]
        j = json.dumps({'titles':trick_titles, 'codes':trick_codes, 'comments': trick_comments}, ensure_ascii=False)
        return HttpResponse(j, status=200)

def tips(request):
    tricks = Trick.objects.all().order_by('id')
    context = {'trick_titles': [x.title for x in tricks],
               'trick_codes': [x.code for x in tricks],
               'trick_comments': [x.comment for x in tricks],
               'tricks': tricks,
               }
    j = json.dumps({'titles': context['trick_titles'], 'codes': context['trick_codes'], 'comments': context['trick_comments']})
    # range_of_len_tips = range(len(trick_titles))
    context['j'] = j
    return render(request, 'tutorial/tipsandtricks.html', context)


def courses(request):
    context = {
        'title': 'Купить курс',
        'courses': Course.objects.all()
    }
    if request.user.is_authenticated:
        context['donated'] = Course.objects.filter(profile__pk=( request.user.profile_set.get(user__pk = request.user.pk)).pk)
    else:
        context['donated'] = []
    return render(request, 'tutorial/courses.html', context)


def page_not_found(request, exception):
    return render(request, 'tutorial/404.html', status=404)


def page_not_found1(request):
    return render(request, 'tutorial/404.html', status=500)

def profile(request):
    user_sols = request.user.usertask_set.filter(user__pk = request.user.pk)
    themes_tasks = {x:[y for y in user_sols.filter(solved_task__pk__in = x.task_set.all())] for x in {x.solved_task.theme for x in user_sols}}
    context = {}
    avr_attemptions = {x.title:(0 if len(themes_tasks[x]) == 0 else sum([i.attemptions for i in themes_tasks[x]])/len(themes_tasks[x])) for x in themes_tasks.keys()}
    context['avr_attemptions'] = json.dumps({'themes':list(avr_attemptions.keys()), 'values':list(avr_attemptions.values())}, ensure_ascii=False)
    avr_ratios = {x.title:(0 if len(themes_tasks[x]) == 0 else sum([i.ratio for i in themes_tasks[x]])/len(themes_tasks[x])) for x in themes_tasks.keys()}
    context['avr_ratios'] = json.dumps({'themes':list(avr_ratios.keys()), 'values':list(avr_ratios.values())}, ensure_ascii=False)
    avr_time = {x.title:(0 if len(themes_tasks[x]) == 0 else sum([(i.finish-i.first_view).total_seconds()/60 for i in themes_tasks[x]])/len(themes_tasks[x])) for x in themes_tasks.keys()}
    context['avr_time'] = json.dumps({'themes':list(avr_time.keys()), 'values':list(avr_time.values())}, ensure_ascii=False)
    return render(request, 'tutorial/profile.html', context)

ksi2/ksi/tutorial/templates/tutorial/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link type="text/css" rel="stylesheet" href="{%static 'tutorial/css/bootstrap.css'%}">
    <link type="text/css" rel="stylesheet" href="{%static 'tutorial/css/style.css'%}">
    <script src="{%static 'tutorial/js/pyodide/pyodide.js'%}" type="text/javascript"></script>
    <script src="{%static 'tutorial/js/bootstrap.bundle.min.js'%}" type="text/javascript"></script>
    <script src="{%static 'tutorial/pyodide.asm.js'%}" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{%static 'tutorial/js/src-min-noconflict/ace.js'%}" type="text/javascript"></script>
</head>
<body class="d-flex flex-column min-vh-100">
<nav class="navbar  navbar-expand-lg navbar-dark bg-dark ">
    <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'tutorial:index'%}">
            <img class="d-block" src="{%static 'tutorial/images/logot.png'%}" alt="" id="logo" width="30px">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
                aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav flex-grow-1 mb-2">
                <li class="nav-item">
                    <a href="/admin" class="nav-link">Админка</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'sandbox'%}" style="color:yellow" class="nav-link  ">Песочница</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'courses'%}" class="nav-link">Курсы</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav  mb-2">
                <li class="nav-item">
                    <a class="nav-link text-info" href="{%url 'profile'%}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#0dcaf0"
                             class="bi bi-person-fill" viewBox="0 0 16 16">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                        </svg>
                        {{request.user.username}}</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'accountksi:logout_user'%}" class="nav-link">Выход</a>
                </li>
            </ul>
            {%else%}
            <ul class="navbar-nav  mb-2">
                <li class="nav-item">
                    <a href="{%url 'accountksi:register'%}?next={{request.path}}" class="nav-link">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'accountksi:login'%}?next={{request.path}}" class="nav-link">Вход</a>
                </li>
            </ul>
            {%endif%}
        </div>
    </div>
</nav>
{% block menu %}
{% endblock %}
{% block content %}
{% endblock %}

<!-- Footer -->
<footer class="text-center text-lg-start  text-muted m-3 mt-auto">
    <section class="border-top">
        Разработка и поддержка учебника: <a href="http://t.me/artpani" class="link-dark text-decoration-none" >Артем Панов</a><br>
        Запуск кода на клиенте осуществляется с помощью <a href="https://pyodide.org/en/stable/" class="link-dark text-decoration-none">Pyodide</a> и <a href="https://ace.c9.io/" class="link-dark text-decoration-none">Ace<a/><br>
        Родилось в 2021
    </section>
    <!-- Section: Links  -->

</footer>
<!-- Footer -->
</body>
</html>

ksi2/ksi/tutorial/templates/tutorial/courses.html
{% extends 'tutorial/base.html' %}
{% load static %}
{% block content %}
<style>
    body{
        background-image:url({%static 'tutorial/images/bg1.svg'%});
        background-repeat: no-repeat
    }
</style>
   


<div class="container py-3">
    <header>
      <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal">Выбор курса</h1>
        <p class="fs-5 text-muted">Автор тоже хочет кушать и поэтому некоторые темы и задачи доступны только после оплаты. Выберите подходящий курс и получите доступ к интересущим материалам.</p>
      </div>
    </header>
  
    <main>
      <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {%for t in courses%}
        <div class="col ">
          <div class="card mb-4 rounded-3 shadow-sm {%if t.priority%}border-success {%endif%}">
            <div class="card-header py-3 {%if t.priority%}text-white bg-success {%endif%}">
              <h4 class="my-0 fw-normal">{{t.title}}</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">₽{{t.price}}</h1>
              <h5 class = 'card-title'>Включает все задачи из тем:</h5>
              <ul class="list-unstyled mt-3 mb-4">
                {%for tms in t.theme.all %}
                <li>{{tms.title}}</li>
                {% endfor %}
                
              </ul>
              <h5 class = 'border-top'>А также задачи:</h5>
              <ul class="list-unstyled mt-3 mb-4">
              {%for tsk in t.task.all %}
              <li>{{tsk.title}}</li>
              {% endfor %}
            </ul>
            {%if t not in donated%}
              <button type="button" class="w-100 btn btn-lg btn-outline-primary mt-2">Купить</button>
            {% else%}
              <button type="button" class="w-100 btn btn-lg btn-success btn-outline-success mt-2" disabled>Вам уже доступен этот курс</button>
            {%endif%}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
  
    </main>
  </div>
  {% endblock %}

ksi2/ksi/tutorial/templates/tutorial/locked_icon.html
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm4 14.083c0-2.145-2.232-2.742-3.943-3.546-1.039-.54-.908-1.829.581-1.916.826-.05 1.675.195 2.443.465l.362-1.647c-.907-.276-1.719-.402-2.443-.421v-1.018h-1v1.067c-1.945.267-2.984 1.487-2.984 2.85 0 2.438 2.847 2.81 3.778 3.243 1.27.568 1.035 1.75-.114 2.011-.997.226-2.269-.168-3.225-.54l-.455 1.644c.894.462 1.965.708 3 .727v.998h1v-1.053c1.657-.232 3.002-1.146 3-2.864z"/></svg>  

ksi2/ksi/tutorial/templates/tutorial/sidebar-menu.html
{% load tutorial_tags %}
<div class="col col-lg-2 ">
            <div class="accordion   open" id="ThemesList">
                {% for t in themes%}
                  <div class="accordion-item rounded border border-dark mt-1">
                    <h2 class="accordion-header p-0 " id="{{t.title_url}}">
                            <button class="pt-0 pb-0 accordion-button {%if t.title_url == theme.title_url%}{%else%}collapsed{%endif%}" type="button" data-bs-toggle="collapse" data-bs-target="#flush-{{t.title_url}}" aria-expanded="false" aria-controls="flush-{{t.title_url}}" role="button">
                                <h5 class="nav-link ms-auto p-0 " >
                                    {{t.title}}
                                    {%if t in locked_themes%}
                                    {%include 'tutorial/locked_icon.html'%}
                                    {% endif %}
                                </h5>
                            </button>
                            {% if request.user.is_authenticated %}
                            <div class="progress position-relative p-0 mt-0" style=" height: 4px;">
                                <div class="progress-bar bg-success" role="progressbar" aria-valuenow="3" aria-valuemin="0" aria-valuemax="100" style="width: {% theme_progress_width request.user t %}%"></div>
                            </div>
                            {%endif%}
                    </h2>
                    <div id="flush-{{t.title_url}}" class="accordion-collapse collapse {%if t.title_url == theme.title_url%}show{%else%}{%endif%}" aria-labelledby="{{t.title_url}}" >
                      <div class="accordion-body p-1">
                          <div class="list-group list-group-flush">
                              <a  class="fst-italic fw-bolder rounded list-group-item list-group-item-action" href="{%url 'tutorial:theory' t.title_url%}">Теория
                                {%if t in locked_themes%}
                                {%include 'tutorial/locked_icon.html'%}
                                {% endif %}
                              </a>
                              {% for taskloop in t.task_set.all %}
                              {% if task == taskloop %}
                              <a  class="rounded list-group-item list-group-item-action " style="background-color:#428bca"  href="{%url 'tutorial:task' t.title_url taskloop.slug%}">{{taskloop.title}}
                                {% if taskloop in locked_tasks%}
                                {%include 'tutorial/locked_icon.html'%}
                                {% endif %}  
                              </a>
                              {%else%}
                              {% if taskloop in st%}
                              <a  class="rounded list-group-item list-group-item-action " style="background-color:rgba(128, 252, 92, 0.3)"  href="{%url 'tutorial:task' t.title_url taskloop.slug%}">{{taskloop.title}}
                                {% if taskloop in locked_tasks%}
                                {%include 'tutorial/locked_icon.html'%}                                
                                {% endif %} </a>
                              {%else%}
                              <a  class="rounded list-group-item list-group-item-action  " style="background-color:rgba(227, 235, 241, 0.7)" href="{%url 'tutorial:task' t.title_url taskloop.slug%}">{{taskloop.title}}
                                {% if taskloop in locked_tasks%}
                                {%include 'tutorial/locked_icon.html'%}                                {% endif %}  
                              </a>
                              {%endif%}
                              {%endif%}
                              {% endfor %}
                          </div>
                      </div>
                    </div>
                  </div>
                {% endfor %}
            </div>
</div>